import { AppShell } from "@/components/AppShell";
import { Link, useLocation } from "react-router-dom";

const policies = {
  privacy: {
    title: "Privacy Policy",
    content: (
      <div className="space-y-4">
        <p><strong>Effective Date:</strong> [Date]</p>
        <p>Lampstand operates with a local-first privacy architecture. By default, your data (journal entries, guidance history, saved passages) is stored locally on your device.</p>
        <h3 className="font-bold mt-4">1. Information We Collect</h3>
        <p>If you choose to create an account, we collect your email address for authentication and optional cloud syncing. Voice inputs are transcribed locally or via an anonymous cloud adapter and are not retained as raw audio by default.</p>
        <h3 className="font-bold mt-4">2. AI Processing</h3>
        <p>Your inputs during Guidance mode are sent securely to our AI providers (e.g., Groq) for real-time processing. These inputs are not used to train the models.</p>
        <h3 className="font-bold mt-4">3. Data Retention</h3>
        <p>You can clear your local data at any time from the Settings page. If you delete your account, your cloud-synced data will be removed from our servers.</p>
        <p className="italic text-sm mt-4 text-muted-foreground">TODO: This document requires review by legal counsel.</p>
      </div>
    )
  },
  terms: {
    title: "Terms of Service",
    content: (
      <div className="space-y-4">
        <p><strong>Effective Date:</strong> [Date]</p>
        <h3 className="font-bold mt-4">1. Acceptance of Terms</h3>
        <p>By using Lampstand, you agree to these Terms of Service. Lampstand is provided by APEX Business Systems LTD.</p>
        <h3 className="font-bold mt-4">2. Use of Service</h3>
        <p>You agree not to misuse the service, attempt to reverse engineer the application, or use the service for abusive purposes.</p>
        <h3 className="font-bold mt-4">3. Disclaimer</h3>
        <p>Lampstand provides spiritual reflection and AI-assisted guidance. It is NOT a replacement for professional counseling, medical advice, or crisis intervention.</p>
        <h3 className="font-bold mt-4">4. Governing Law</h3>
        <p>These terms are governed by the laws of Alberta, Canada.</p>
        <p className="italic text-sm mt-4 text-muted-foreground">TODO: This document requires review by legal counsel.</p>
      </div>
    )
  },
  acceptable: {
    title: "Acceptable Use Policy",
    content: (
      <div className="space-y-4">
        <p>You agree to use Lampstand in a manner consistent with its purpose as a spiritual companion.</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Do not use the service to generate harmful, abusive, or explicit content.</li>
          <li>Do not attempt to scrape or programmatically extract data from the service.</li>
          <li>Do not attempt to bypass safety filters or inject malicious prompts.</li>
        </ul>
        <p className="italic text-sm mt-4 text-muted-foreground">TODO: This document requires review by legal counsel.</p>
      </div>
    )
  },
  disclaimer: {
    title: "AI and Spiritual Guidance Disclaimer",
    content: (
      <div className="space-y-4">
        <p>Lampstand utilizes artificial intelligence to provide scriptural context, reflections, and prayers.</p>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Not a Human:</strong> The responses are generated by AI and may occasionally lack the nuance of a human pastor or counselor.</li>
          <li><strong>Not Professional Advice:</strong> Lampstand is not a substitute for professional mental health care. If you are in crisis, please contact emergency services.</li>
          <li><strong>Theological Review:</strong> While we strive for theological soundness rooted in scripture, you are encouraged to read the Bible directly and consult with your local church community.</li>
        </ul>
        <p className="italic text-sm mt-4 text-muted-foreground">TODO: This document requires review by legal counsel.</p>
      </div>
    )
  }
};

const LegalPage = () => {
  const location = useLocation();
  const path = location.pathname.split("/").pop();
  const policyKey = path as keyof typeof policies;
  const policy = policies[policyKey] || policies.terms;

  return (
    <AppShell>
      <div className="max-w-3xl mx-auto py-12 px-6">
        <div className="mb-8 flex gap-4 text-sm overflow-x-auto pb-4">
          <Link to="/legal/privacy" className={`hover:text-primary whitespace-nowrap ${policyKey === 'privacy' ? 'font-bold text-primary' : 'text-muted-foreground'}`}>Privacy Policy</Link>
          <Link to="/legal/terms" className={`hover:text-primary whitespace-nowrap ${policyKey === 'terms' ? 'font-bold text-primary' : 'text-muted-foreground'}`}>Terms of Service</Link>
          <Link to="/legal/acceptable" className={`hover:text-primary whitespace-nowrap ${policyKey === 'acceptable' ? 'font-bold text-primary' : 'text-muted-foreground'}`}>Acceptable Use</Link>
          <Link to="/legal/disclaimer" className={`hover:text-primary whitespace-nowrap ${policyKey === 'disclaimer' ? 'font-bold text-primary' : 'text-muted-foreground'}`}>AI Disclaimer</Link>
        </div>

        <div className="bg-card border rounded-lg p-8 shadow-sm">
          <h1 className="text-3xl font-serif font-bold mb-6 text-foreground">{policy.title}</h1>
          <div className="font-sans text-foreground/80 leading-relaxed">
            {policy.content}
          </div>
        </div>

        <div className="mt-12 text-center text-sm text-muted-foreground border-t pt-8">
          <p>© {new Date().getFullYear()} APEX Business Systems LTD. All rights reserved.</p>
          <p className="mt-2">Proprietary software. Limited license granted to end users subject to the Terms of Service.</p>
        </div>
      </div>
    </AppShell>
  );
};

export default LegalPage;
