// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfqivpqedhmgyqwqpwim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcWl2cHFlZGhtZ3lxd3Fwd2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MjM5NjIsImV4cCI6MjA5MTE5OTk2Mn0.ekGcJLFYalRwJtCS4WWlEBVHIj3i4RytzTl1hW6xMpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});